corrigindo leitura -> lendo sempre o último índice
dadosjusbr/coletor-mpmg pull request #7
Opened 2024-05-13 17:40 UTC by joellensilva

- corrigindo erro de coleta: "Error 7: error loading datapackage (/home/runner/work/executor-automatizado/executor-automatizado/output/mpmg_01_2024/output/mpmg-2024-1.zip):\"failed to cast ContraCheque_CSV: [{0 the row with 0 values does not match the 13 fields in the schema}]\""
- erro se dava devido ao campo **folha** do proto estar vazia, que por sua vez acontecia devido ao coletor não acessar o índice da planilha corretamente.

2024-05-13 20:53 UTC, JezzDiego reviewed
Esse item é novo no índice/foi adicionado recentemente?

2024-05-14 13:10 UTC, joellensilva commented
Kkkkk não se preocupa

Este coletor acessa os dados em um html, ao converter para o pandas.DataFrame temos um objeto com 1 ou 2 posições, nesse caso. Antes os dados estavam na primeira posição/índice desse objeto [0], agora estão na segunda [1]. 

De toda forma, ao acessar com [-1], sempre acessamos a última posição desse objeto, o que funciona com as planilhas mais antigas e com essa atual.

Já a questão do proto, que é passado entre as etapas do pipeline, tem alguns campos: coleta, metadados, folha... (não recordo os nomes agora). Esses campos são preenchidos com todos os dados da coleta para empacotar/armazenar depois. O campo **folha**, que comentei, é no qual ficam os dados dos membros, com suas rubricas e valores. E nesse caso tava ficando vazia por não achar os membros :clown_face: 

@JezzDiego

2024-05-14 14:50 UTC, danielfireman requested changes

2024-05-14 14:50 UTC, danielfireman commented on src/data.py
> +        data = data[-1]
Pra que fazer data receber a última posição se logo na linha seguinte iremos fazer a mesma variável receber um arranjo.

Acho que podemos apenas remover essa linha.

2024-05-14 20:52 UTC, joellensilva commented on src/data.py
> +        data = data[-1]
Não deu (_Erro lendo as planilhas: 'list' object has no attribute 'to_numpy'_), a variável **data** ainda precisa receber a última posição, pois a função **read_html** retorna uma lista de DataFrame. Mas de fato, após isso o arranjo na linha seguinte é dispensável. Removi.

2024-05-14 21:20 UTC, danielfireman commented on src/data.py
> +        data = data[-1]
Ahh .. beleza!

2024-05-14 21:20 UTC, danielfireman approved these changes

2024-05-15 19:45 UTC, JezzDiego approved these changes

2024-05-15 21:20 UTC, merged